### ISSUE TITLE
numpy-1.19.4-cp36-none-manylinux2014_aarch64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by wwj718** [feitgemel/Jetson-Nano-Python#1]
When I run on [JETSON NANO 2GB](https://www.nvidia.com/en-sg/autonomous-machines/embedded-systems/jetson-nano/education-projects/), I met the error:

![image](https://user-images.githubusercontent.com/3153878/133412879-58c3cdbe-b347-44d1-858b-1c157461dd2a.png)

the result of `uname -a` as the same as Jetson nano:

```
nano-2g@nano2g-desktop:~/mediapipe-bin$ uname -a
Linux nano2g-desktop 4.9.253-tegra #1 SMP PREEMPT Mon Jul 26 12:13:06 PDT 2021 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by mcwhorpj** [comment]
Thank you for this useful instruction. In following your instructions, and the new information in comments above, I have mediapipe running on jetpack 4.6.1 . The problem I have, as others have mentioned, gstreamer is disabled, and hence raspberry pi camera is rendered not usable. I have read that the cmake must have WITH_GSTREAMER and WITH_GSTREAMER_0_10 set to ON during installation. Does anyone have any ideas how the instructions here would be modified so the end result allows gstreamer and hence the pi camera. Any help would be greatly appreciated.
Thanks,
